kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: eignhpants/ecr-puller
    username: 
      from_secret: dh_user_name
    password: 
      from_secret: dh_pw    
  publish:
    image: eignhpants/ecr-puller
